import { Matcha } from '@/types/matcha';

export const dummyMatcha: Matcha[] = [
  {
    id: 1,
    name: "抹茶かき氷",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 1,
    user_id: 1,
    price: 500,
  },
  {
    id: 2,
    name: "抹茶ラテ",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 2,
    date: new Date(),
    shop_id: 2,
    user_id: 1,
    price: 300,
  },
  {
    id: 3,
    name: "抹茶パフェ",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 3,
    user_id: 1,
    price: 800,
  },
  {
    id: 4,
    name: "抹茶クッキー",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 4,
    user_id: 1,
    price: 200,
  },
  {
    id: 5,
    name: "抹茶アイス",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 5,
    user_id: 1,
    price: 150,
  },
  {
    id: 6,
    name: "抹茶ケーキ",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 6,
    user_id: 1,
    price: 600,
  },
  {
    id: 7,
    name: "抹茶プリン",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 7,
    user_id: 1,
    price: 400,
  },
  {
    id: 8,
    name: "抹茶クレープ",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 8,
    user_id: 1,
    price: 700,
  },
  {
    id: 9,
    name: "抹茶モンブラン",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 9,
    user_id: 1,
    price: 900,
  },
  {
    id: 10,
    name: "抹茶チョコ",
    imageUrl: "/dummyMatcha.jpg",
    genre_id: 1,
    date: new Date(),
    shop_id: 10,
    user_id: 1,
    price: 250,
  },
];