import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <style>
        {`
          .container {
            max-width: 414px;
            with: 100%;
            margin: 0 auto;
            padding: 0 1rem;
            background-color: #fff;
          }
        `}
      </style>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
